# ==================== Server ====================
server:
  port: 8085

# ==================== Database ====================
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/kinopoiskdb?useSSL=false&serverTimezone=UTC"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # ==================== JPA ====================
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 10
        order_inserts: true
    show-sql: true

  # ==================== Flyway ====================
  flyway:
    baseline-on-migrate: true
    baseline-version: 1

  # ==================== Spring Kafka ====================
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${kafka.consumer.group-id:movie-email-consumer-group}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true
      auto-commit-interval: 1000
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      batch-size: 16384
      linger-ms: 1
      buffer-memory: 33554432

  # ==================== Spring Mail ====================
  mail:
    host: smtp.yandex.ru
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

# ==================== Scheduler ====================
scheduler:
  enabled: true
  cron: "0 * * * * *"

# ==================== Daily Genre Schedule ====================
daily-genre:
  schedule:
    MONDAY: "драма"
    TUESDAY: "комедия"
    WEDNESDAY: "боевик"
    THURSDAY: "фантастика"
    FRIDAY: "триллер"
    SATURDAY: "приключения"
    SUNDAY: "мультфильм"

# ==================== Kafka Topics ====================
kafka:
  topics:
    movie-daily: "movie-daily-topic"
  consumer:
    group-id: "movie-email-consumer-group"
    batch-size: 50

# ==================== Kinopoisk API ====================
kinopoisk:
  api:
    url: "${kinopoisk.api.url:https://kinopoiskapiunofficial.tech/api/v2.2/films}"
    token: ${KINOPOISK_API_TOKEN}
    page-size: 50
    key: ${KINOPOISK_API_TOKEN}

# ==================== Email Settings ====================
email:
  daily-report:
    recipient: "mym99527@gmail.com"
    subject-prefix: "Фильмы"